language: python
python:
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install pipenv check-pipfile-lock
script:
  - check-pipfile-lock
  - pipenv install --system --dev
  - flake8
  - mypy .
