from envparse import env  # type: ignore

TELEGRAM_TOKEN = env.str("TELEGRAM_TOKEN")

PROXY_URI = env.str("PROXY_URI", default="")
PROXY_LOGIN = env.str("PROXY_LOGIN", default="")
PROXY_PASSWORD = env.str("PROXY_PASSWORD", default="")

POSTGRES_HOST = env.str("POSTGRES_HOST")
POSTGRES_PORT = env.int("POSTGRES_PORT")
POSTGRES_USER = env.str("POSTGRES_USER")
POSTGRES_PASSWORD = env.str("POSTGRES_PASSWORD")
POSTGRES_DB = env.str("POSTGRES_DB")
POSTGRES_URI = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
