version: "3"

services:
    postgres:
        image: "postgres:12.3"
        restart: on-failure
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB:
            POSTGRES_USER:
            POSTGRES_PASSWORD:
    app:
        build: .
        restart: on-failure
        depends_on:
            - postgres
        environment:
            TELEGRAM_TOKEN:

            PROXY_URI:
            PROXY_LOGIN:
            PROXY_PASSWORD:

            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_DB:
            POSTGRES_USER:
            POSTGRES_PASSWORD:
