"""Add play_wolf_game column to chat_member

Revision ID: 977e96c98ef5
Revises: bff61ca896f3
Create Date: 2021-01-24 16:57:30.264399

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '977e96c98ef5'
down_revision = 'bff61ca896f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_members', sa.Column('play_wolf_game', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_members', 'play_wolf_game')
    # ### end Alembic commands ###
